### PR TITLE
Add less and scss to main in bower

### PR DESCRIPTION
**Pull request by stevemao**
Make `wiredep` or other bower tools work for less and scss version.

### CODE REVIEW

**Comment by cvrebert** [comment]
Also, per the updated `bower.json` spec for `main` (https://github.com/bower/bower.json-spec/commit/0b34d2bb0bdd4fa31fa9728f787f49e170e41f99):
* CSS should be excluded if the Less/Sass it's generated from is included
* Globs are invalid
* Font files shouldn't be included (tools are supposed to detect them based on extension/file-type or by virtue of them being referenced in the Less/Sass/CSS)

**Comment by tagliala** [comment]
so it should be

```json
"main": [
  "less/font-awesome.less",
  "scss/font-awesome.scss"
],
```

?

**Comment by cvrebert** [comment]
Correct.

**Comment by tagliala** [comment]
@cvrebert thanks

@stevemao could you please update this PR and force push?

**Comment by stevemao** [comment]
Done. But what if people are not use scss or less but just css?

**Comment by tagliala** [comment]
@stevemao I've just read this blogpost

http://blog.getbootstrap.com/2015/06/15/bootstrap-3-3-5-released/#wiredep-and-bower

does it help you?

**Comment by stevemao** [comment]
Yes, that's exactly what concerns me. 
https://github.com/bower/bower.json-spec/issues/47 should resolve this

**Comment by tagliala** [comment]
Done via https://github.com/FortAwesome/Font-Awesome/commit/11884523464c05869d4b6e5484d538c049654bbe

thanks!

closing here

**Comment by tagliala** [comment]
Sorry for this breaking change but please use overrides

```json
  "overrides": {
    "font-awesome": {
      "main": [
        "./css/font-awesome.css",
        "./fonts/*"
      ]
    }
  }
```

Refers to https://github.com/twbs/bootstrap/issues/16663

**Pull request closed without merging**
