### PR TITLE
Update UPGRADING.md (1)

### PR DESCRIPTION
**Pull request by jbelien**
Add missing `import dom` and `dom.watch()`

I understand that:

- [x] I'm submitting this PR for reference only. It shows an example of what I'd like to see changed but
  I understand that it will not be merged and I will not be listed as a contributor on this project.

### CODE REVIEW

**Comment by robmadole** [comment]
Great find. Thanks @jbelien

**Comment by jbelien** [comment]
You're very welcome !

**Comment by tagliala** [comment]
@robmadole isn't this going to be overwritten by the changes in the build system?

**Comment by robmadole** [comment]
@tagliala nah, this one isn't touched

**Pull request merged**
