### PR TITLE
Change link to https://fortawesome.com/start

### PR DESCRIPTION
**Pull request by pra85**
Also changed the link from https://fonticons.com to https://fortawesome.com/start as it was redirected to homepage

### CODE REVIEW

**Comment by tagliala** [comment]
Thanks. just need some feedback from Dave on this one before merging

**Comment by davegandy** [comment]
URL change looks great! However, I'd like to keep it a .txt file, as I want the file readable on all systems.

**Comment by pra85** [comment]
@davegandy I have updated the pull request which only changes the link to https://fortawesome.com/start

**Comment by tagliala** [comment]
Merged, thanks!

**Comment by tagliala** [comment]
wrong file edited. The proper file to edit is https://github.com/FortAwesome/Font-Awesome/blob/master/src/assets/font-awesome/HELP-US-OUT.txt

**Comment by pra85** [comment]
@tagliala Created a seperate pull request for that - https://github.com/FortAwesome/Font-Awesome/pull/8429

**Pull request merged**
