### PR TITLE
Add fa-xl size class, between fa-lg and fa-2x

### PR DESCRIPTION
**Pull request by johnnyshields**
Add fa-xl size class, between fa-lg and fa-2x

### CODE REVIEW

**Comment by johnnyshields** [comment]
Can someone please look at this? I use this in nearly all my projects, its very useful.

**Comment by hien-** [comment]
+1

**Comment by zuck** [comment]
+1

**Comment by robmadole** [comment]
First off, thanks for spending the time to post this PR. It's sat in the Font Awesome GitHub repo for far too long and we should have responded or addressed the work that you put into this.

Over the past year we've been hard at work on Font Awesome 5. It's now released and this PR no longer applies. So we're going to close it (with an apology for being so tardy).

If you think the work from this still applies feel free to reply and we'll take a second look.

– FA team

**Pull request closed without merging**
