### PR TITLE
Update teamspeak.svg

### PR DESCRIPTION
**Pull request by Azn9**
Update the icon to match teamspeak's branding changes
Ref: #18924 

I understand that:

- [x] I'm submitting this PR for reference only. It shows an example of what I'd like to see changed but
  I understand that it will not be merged and I will not be listed as a contributor on this project.

### CODE REVIEW

**Comment by tagliala** [comment]
Hi, is this an official logo? If it is, is there a link to an official svg on teamspeak's website?

**Comment by Azn9** [comment]
It is a modified version of the official logo, without the text. The original can be found here: https://www.teamspeak.com/user/themes/teamspeak/images/logo.svg

**Comment by olokos** [comment]
Isn't this the latest original logo?
https://teamspeak.com/user/themes/teamspeak/images/favicon.ico

I know the one in this PR is on the top of the page, but the real logo/icon of the app is  the favicon

**Comment by Azn9** [comment]
> Isn't this the latest original logo?
> https://teamspeak.com/user/themes/teamspeak/images/favicon.ico
> 
> I know the one in this PR is on the top of the page, but the real logo/icon of the app is  the favicon

That's the app icon, not the Teamspeak brand's logo. (Yes they're different)

https://community.teamspeak.com/t/new-media-pack-branding-page/22628

**Comment by olokos** [comment]
I stand corrected, this should definitely be merged.
@tagliala 
The source material is also provided in the link above

**Comment by sensibleworld** [comment]
Updated in 6.4.0: https://fontawesome.com/icons/teamspeak?f=brands&s=solid

**Pull request closed without merging**
