### PR TITLE
adding nested icon classes and examples

### PR DESCRIPTION
**Pull request by andrewmck**
Adding the ability to nest and position icons within other icons.  

The changes have been tested (through BrowserStack.com) with:

Windows 7
  - IE 8+
  - FireFox 3.6 + 
  - Safari 4+
  - Chrome 14+
  - Opera 10.6+

OSX
  - Safari 4+
  - FireFox 4+
  - Chrome 14+
  - Opera 11.1+

Android
  - 2.2 +

iPhone
  - IOS 4+

iPad
  - IOS 4.3.2+

Opera Mini

Windows Phone 8.1

### CODE REVIEW

**Comment by williamboman** [comment]
@andrewmck I fixed/added some minor stuff, https://github.com/andrewmck/Font-Awesome/pull/1.

**Comment by tagliala** [comment]
thanks guys!

I don't think the 4.3.1-wip is the proper branch for this, 4.3.1 is only supposed to contain fixes. But I also don't know Dave's plans...

Any chance of seeing a live demo of this feature instead of downloading repo and build docs?

**Comment by williamboman** [comment]
@tagliala You can temporarily view it here: http://williamboman.github.io/Font-Awesome/examples/#nested

**Comment by tagliala** [comment]
@williamboman thanks

There are still issues in the example indentation (it should be 2 spaces)

I'm wondering if this could entirely replace stacked icons

**Comment by x2nie** [comment]
Hi all,

I think the stacked icons is yet powerful.
Using stacked icons style, I can reproduce what the nested style can do.

Here is my code of Phone Comment Exclamation (one of nested sample)
'''
<span class="fa-stack fa-2x">
          <i class="fa fa-mobile fa-stack-2x"></i>
          <i class="fa fa-comment fa-stack-1x" style="
    top: 0;
    left: inherit;
    color: skyblue;
    height: 1em;
    line-height: 1em;
    width: 1em;
    right: 0;
"></i>
			<i class="fa fa-exclamation fa-stack-1x fa-inverse" style="
    font-size: .5em;
    left: inherit;
    right: .5em;
    height: 1em;
    line-height: 1em;
    top: 0.5em;
    width: 1em;
"></i>
        </span>mobile exclamation<br>
'''

Okay, my mod isn't supplied with css-class, but I think it just prove

**Comment by tagliala** [comment]
could we try to extend stacked icons with new styles instead of creating a similar feature?

**Comment by x2nie** [comment]
@tagliala, sure!
in my code above, I put all of the needed css inplace of each element.
To extend stacked icons to have the nested features, we should break down them (needed css) into separated classes, if we want they (the needed class) are being useful. 

We can reuse some of class available in the nested such as `align-tr` for aligning the icon into top right and so on.

**Comment by x2nie** [comment]
Hi !

here is what I am talking about
screenshot:
image

html:
```
<span class="fa-stack fa-2x">
  <i class="fa fa-mobile fa-stack-2x"></i>
  <i class="fa fa-comment fa-stack-1x fa-t0 fa-r0 text-danger" ></i>
  <i class="fa fa-exclamation fa-stack-1x fa-05x fa-t05 fa-r05 fa-inverse" ></i>
</span>mobile exclamation<br>
```

css:
```
.fa-05x {
	font-size: .5em;
}
.fa-t0, .fa-t025, .fa-t05{
	height: 1em;
	line-height: 1em;
}

.fa-t0 {
	top: 0;
}
.fa-t025 {
	top: .25em;
}
.fa-t05 {
	top: .5em;
}

.fa-l0, .fa-l025, .fa-l05,
.fa-r0, .fa-r025, .fa-r05 {
	width: 1em;
	left: inherit;
}
.fa-r0 {
	right: 0;
}
.fa-r025 {
	right: .25em;
}
.fa-r05 {
	right: .5em;
}
```
the `fa-05x` is an extension of known size like `fa-2x`, `fa-3x`, `fa-4x` and so

Anyway, well, I know nothing about Less or Saas. I can't supply the patch of the Less or Saas.
I hope you like it

**Comment by x2nie** [comment]
using above css, here is the same bullseye constructed using stacked icon

image

**nested use**
```
<!-- four deep nesting with size adjustments -->
<i class="fa fa-nest fa-circle fa-4x">
  <i class="fa fa-circle text-danger lg">
	<i class="fa fa-circle text-info lg">
	<i class="fa fa-circle fa-inverse"></i>
  </i>
  </i>
</i>
bullseye<br>
```


**stacked icons use**
```
<!-- four deep non nesting with size adjustments -->
<span class="fa-stack fa-2x">
	<i class="fa fa-circle fa-stack-2x "></i>
	<i class="fa fa-circle fa-stack-1x fa-1-5x text-danger"></i>
	<i class="fa fa-circle fa-stack-1x text-info"></i>
	<i class="fa fa-circle fa-stack-1x fa-05x fa-inverse"></i>
 </span>
bullseye<br>
```

**Comment by x2nie** [comment]
one more sample, 
if you look at fontawesome's blog, there is [adjusted icon sample] (http://blog.fontawesome.io/2014/09/25/custom-file-types-with-stacked-icons/)
while using my **css above** can be constructed using current fontawesome css.
> note: the sample in the blog can't be combined with official one because both are incompatible

Okay, here is the mod:
```
<span class="fa-stack fa-2x">
  <i class="fa fa-gear fa-stack-1x fa-t075"></i>
  <i class="fa fa-file-o fa-stack-2x"></i>
</span> 
Custom File Type non hacked
```

preview : 
image

**Pull request closed without merging**
