### PR TITLE
remove new line in the end of file

### PR DESCRIPTION
**Pull request by rinick**
this svg has an extra new line, it should be removed to keep file format consistent

### CODE REVIEW

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this PR.

Sorry, I don't see changed files, could you please check again?

**Comment by rinick** [comment]
@tagliala the file is `svgs/brands/keybase.svg`, all the other files are one line svg, but this one has a new line in the end.
I'm not sure why github thinks there is no file change :(

**Comment by tagliala** [comment]
Oh thanks, that file changed recently. But I still can't see two lines

**Comment by rinick** [comment]
> Oh thanks, that file changed recently. But I still can't see two lines

try this link, you should see the second line
https://github.com/FortAwesome/Font-Awesome/edit/master/svgs/brands/keybase.svg

**Comment by tagliala** [comment]
@rinick ok thanks, I can confirm. This should be fixed upstream in our build system

**Comment by tagliala** [comment]
@rinick thanks, this will be fixed in the next release.

**Pull request closed without merging**
