### PR TITLE
fa: add government alias

### PR DESCRIPTION
**Pull request by Joery**
Add fa-government alias to the existing fa-university icon

### CODE REVIEW

**Comment by wolfy1339** [comment]
Please dont edit generated css files. Only edit the proper .yml file (maybe someone knows the name)

**Comment by Joery** [comment]
Ah, thanks. I'll create a new PR.
For reference, you can find this under \src\icons.yml

**Comment by tagliala** [comment]
@Joery please add a filter, not an alias

so you will still need to alias `fa-government` to `fa-university` in your own application but when you search for `government` at http://fontawesome.io/icons/ you will find the icon you need

**Comment by Joery** [comment]
#8226

**Pull request closed without merging**
