### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by jisaacks** [comment]
According to the `package.json` [docs](https://docs.npmjs.com/files/package.json#license) the current way is closer to what is recommended for multiple licenses.

**Comment by PeterDaveHello** [comment]
Updated!

**Comment by tagliala** [comment]
the operator should be AND, am I right?

* The Font Awesome font is licensed under the SIL OFL 1.1:
http://scripts.sil.org/OFL
* Font Awesome CSS, LESS, and Sass files are licensed under the MIT License:
http://opensource.org/licenses/mit-license.html

**Comment by jisaacks** [comment]
> the operator should be AND, am I right?

I would tend to agree, that is also valid SPDX.

So in that sense, this PR really just needs to add the wrapping parens.

**Comment by PeterDaveHello** [comment]
oops, so I think I should close this, sorry.

**Comment by tagliala** [comment]
@PeterDaveHello I suppose we still need parentheses

**Comment by PeterDaveHello** [comment]
Oh okay

**Comment by tagliala** [comment]
Thanks. Merging because of https://docs.npmjs.com/files/package.json#license

> If your package is licensed under multiple common licenses, use an SPDX license expression syntax version 2.0 string, like this:
```{ "license" : "(ISC OR GPL-3.0)" }```

I'm still worried about breaking backward compatibility but let's follow the specs

**Comment by PeterDaveHello** [comment]
:+1:

**Pull request merged**
