### PR TITLE
Add feature to customize line-height-base

### LINKED ISSUE #6249: make line-height configurable
in `_core.scss`

I've modified this in my own codebase to support my vertical code base's line-height.

this is necessary so the icons sit correctly in vertical alignment

I suggest a `$fa-line-height-base` variable. I can create a pull-request if you want 

``` scss
.#{$fa-css-prefix} {
  display: inline-block;
 // the line below is modified
  font: normal normal normal #{$fa-font-size-base}/#{$fa-line-height-base} FontAwesome; // shortening font declaration
  font-size: inherit; // can't have font-size inherit on line above, so need to override
  text-rendering: auto; // optimizelegibility throws things off #1094
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transform: translate(0, 0); // ensures no half-pixel rendering in firefox

}
```

### PR DESCRIPTION
**Pull request by lifeiscontent**
Fixes #6249

### CODE REVIEW

**Comment by lifeiscontent** [comment]
CC: @tagliala

**Comment by lifeiscontent** [comment]
Please let me know if I missed anything, first time contributing to this repo.

**Comment by tagliala** [comment]
Looks good to me, thanks

**Comment by lifeiscontent** [comment]
@tagliala Yeah no worries. I'm really glad I did this, I saw your iCare project and I'm really inspired by the quality of code you two guys have written :+1:

**Pull request merged**
