### PR TITLE
.fa { text-indent: 0; }

### PR DESCRIPTION
**Pull request by Mr21**
Hi again @tagliala :)

After your response here: #5750 I have applied your change.

So I propose to add `text-indent: 0;` in the core of Font-Awesome (in the class `.fa`).
To counter this probleme: http://jsfiddle.net/Mr21/pft9gL4v/

Thanks for you help.

### CODE REVIEW

**Comment by msieurtoph** [comment]
Don't know what you mean by "waiting for feedback" ... but I am using the same fix for this issue, and I have not noticed any regression so far.

**Comment by tagliala** [comment]
@msieurtoph I need feedback from Dave

**Comment by Mr21** [comment]
Hi :)

Finally I change `initial` by `0`.
Less charactere and... **IE 11** doesn't know this keyword...

**Comment by Mr21** [comment]
@davegandy, @tagliala is there some news?

**Comment by Mr21** [comment]
@davegandy, what is the problem?

**Comment by Mr21** [comment]
@davegandy @tagliala

**Comment by tagliala** [comment]
@Mr21 sorry, I don't know

**Pull request closed without merging**
