### PR TITLE
4.7.0 Minor Release

### PR DESCRIPTION
**Pull request by davegandy**
Calling this a minor release as we're adding some several new icons.

A huge thanks goes out to Linode, who sponsored the top 5 most requested icons being made.

---
#### New Icons
- [x] #878 - Add handshake-o icon (thanks, Linode!)
- [x] #897 - Add envelope-open icon (thanks, Linode!)
- [x] #708 - Add bath, shower icons (thanks, Linode!)
- [x] #825 - Add id-card, address-book icons (thanks, Linode!)
- [x] #720 - Add thermometer icon (thanks, Linode!)
- [x] #9806 - Add Linode logo
- [x] #6927 - Add Free Code Camp logo
#### Updated icons
- [x] #9633 - Update Mastercard logo
- [ ] ~~#9368 - Update QQ logo~~

All issues in milestone: [4.7.0 milestone](https://github.com/FortAwesome/Font-Awesome/issues?q=milestone%3A4.7.0+is%3Aclosed)

---
### Release Checklist
- [x] Update config.yml with latest version numbers
- [x] Set up PR for release
- [x] Update component.json, package.json, composer.json
- [x] Update README with link to this PR
- [x] Update font file info to latest version
- [x] Generate webfont files from OTF via Font Squirrel
- [x] Make sure code points to webfont files, not OTF
- [x] Double-check height in /test/height
- [x] Ensure exported TTF is set to installable with ttembed (Font Squirrel breaks it, need to fix after)
- [ ] Update Font Awesome CDN
- [ ] Alert MaxCDN of new version
- [x] Release
- [ ] Update Algolia search
- [ ] Alert Travis to update SASS & LESS gems

### CODE REVIEW

**Comment by luke-barnett** [comment]
@davegandy I have a project that is dependent on one of the new icons. When is the estimate release date? Is there anything that could be done to aid the release of 4.7?

**Comment by BENDERJKE** [comment]
Hi!
Add the icon of "telegramm" without a circle

**Comment by tagliala** [comment]
@BENDERJKE please start a new request following https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by lisboeta** [comment]
Hi,
Is it possible to make route and weather icons?

Thanks.

**Comment by tagliala** [comment]
@lisboeta weather: #155 , about a route, please take a look here: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by KanikaChoudhary1313** [comment]
Can you please share updated  fontawesome-markers.min.js for font awesoe version 4.7.0

**Comment by KanikaChoudhary1313** [comment]
or how to create markers min.js for new icons like exclamation triangle ?

**Comment by tagliala** [comment]
@KanikaChoudhary1313 what is `fontawesome-markers.min.js` ?

**Comment by PeterShaggyNoble** [comment]
@tagliala, Google leads me to suspect that @KanikaChoudhary1313 may be referring to [this project](https://github.com/nathan-muir/fontawesome-markers), not realising it's not an official FA project.

**Comment by tagliala** [comment]
@PeterShaggyNoble thanks for the clarification

**Comment by b7r3333** [comment]
Vcc

**Pull request merged**
