### PR TITLE
Icon update: ravelry.svg

### PR DESCRIPTION
**Pull request by outcassed**
Ravelry has rebranded, this is the new icon

I understand that:

- [X] I'm submitting this PR for reference only. It shows an example of what I'd like to see changed but
  I understand that it will not be merged and I will not be listed as a contributor on this project.

### CODE REVIEW

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this PR.

We cannot merge this because this needs to be fixed in our upstream, @sensibleworld will take care of using the official SVG in our next update

PS: I've noticed that the top left side of the circle shape is not perfect, is this a design choice?

image

**Comment by outcassed** [comment]
> I've noticed that the upper left quadrant of the circle is not perfect, is this a design choice?

It is! - it's a lumpy ball of yarn (affectionately named... "lumpy")

**Comment by tagliala** [comment]
Hi @sensibleworld , please remember this change for the next update

**Comment by sensibleworld** [comment]
Thanks for the reminder, @tagliala!

**Comment by tagliala** [comment]
Fixed upstream in 5.15.1

**Pull request closed without merging**
