### PR TITLE
Use autoprefixer

### LINKED ISSUE #2738: Use Autoprefixer
Font Awesome CSS contains a lot of outdated prefixes. [Autoprefixer](https://github.com/ai/autoprefixer) can clean it.

### PR DESCRIPTION
**Pull request by realityking**
Closes #2738 

As an aside, having to install less & plugins globally is, well, less than ideal.

### CODE REVIEW

**Comment by realityking** [comment]
Any news on this?

**Comment by tagliala** [comment]
Hi,

I would really like to use autoprefixer but I can't make this decision, sorry

Also, I would also like to use a better build process based on grunt, like in #1166

**Comment by realityking** [comment]
I know this is something @davegandy has to review - I just don't know how to trigger a review from him ;)

As for the better build process, that's orthogonal to this pull requests as autoprefixer works with the current build process and could just as easily be incorporated into a grunt/gulp/whatever process.

**Comment by robmadole** [comment]
First off, thanks for spending the time to post this PR. It's sat in the Font Awesome GitHub repo for far too long and we should have responded or addressed the work that you put into this.

Over the past year we've been hard at work on Font Awesome 5. It's now released and this PR no longer applies. So we're going to close it (with an apology for being so tardy).

If you think the work from this still applies feel free to reply and we'll take a second look.

– FA team

**Pull request closed without merging**
