### PR TITLE
fix: bug with `!default` for `fa-font-display` variable

### PR DESCRIPTION
**Pull request by evilebottnawi**
I understand that:

- [x] I'm submitting this PR for reference only. It shows an example of what I'd like to see changed but
  I understand that it will not be merged and I will not be listed as a contributor on this project.

Impossible change value. I think it is bug and need fix asap, thanks!

### CODE REVIEW

**Comment by tagliala** [comment]
Thanks

**Comment by tagliala** [comment]
Nope, sorry.

**Comment by robmadole** [comment]
This will get released in the next version of Font Awesome.

**Comment by tagliala** [comment]
Fixed in 5.8.0

Thanks again!

https://github.com/FortAwesome/Font-Awesome/blob/5.8.0/scss/_variables.scss#L6
https://github.com/FortAwesome/Font-Awesome/blob/5.8.0/js-packages/%40fortawesome/fontawesome-free/scss/_variables.scss#L6

**Pull request closed without merging**
