### PR TITLE
New spinning effect for fa-spinner

### PR DESCRIPTION
**Pull request by Seb33300**
This is a new effect more appropriated for the fa-spinner icon.
I don't know how to compile scss and less into css in the main directory.
Nothing specified about that in the guidelines.

### CODE REVIEW

**Comment by skoub** [comment]
The problem seems to come from the icon itself. If you take the Icomoon spinner version, it does'nt wobble at all.
http://jsfiddle.net/cxxzh0uf/

**Comment by tagliala** [comment]
@skoub please post your comment about the spin wobble here: #671, I'm interested and I have a clue

**Comment by skoub** [comment]
@tagliala, i added the comment to the #671 thread.

**Comment by Seb33300** [comment]
Better implementation in #4456

**Pull request closed without merging**
