### PR TITLE
Sass: List var of all icons

### PR DESCRIPTION
**Pull request by CupOfTea696**
Adds a list variable of all icons to easily loop through

### CODE REVIEW

**Comment by ketan** [comment]
+1 - it would be great to see this change, so that font awesome is more usable with sass mixin frameworks.

I'm happy to rebase and submit a new PR if the maintainers are OK with this change, OR have a better idea to refactor the variables file so it's easier to "lookup" icons.

**Comment by XiBOR** [comment]
+1

**Comment by drmonkeyninja** [comment]
This seems like a really good idea as it would surely make the Sass not only more usable but also easier to maintain as adding new icons would be as simple as adding a new icon to the list. Is there any chance of this being revisited and actually accepted into the master branch?

**Comment by Matthew-Bonner** [comment]
Can you change the title from SASS to Sass. See:
https://github.com/FortAwesome/Font-Awesome/pull/8170

**Comment by robmadole** [comment]
First off, thanks for spending the time to post this PR. It's sat in the Font Awesome GitHub repo for far too long and we should have responded or addressed the work that you put into this.

Over the past year we've been hard at work on Font Awesome 5. It's now released and this PR no longer applies. So we're going to close it (with an apology for being so tardy).

If you think the work from this still applies feel free to reply and we'll take a second look.

– FA team

**Pull request closed without merging**
