### PR TITLE
Update versions for component.json and package.json

### PR DESCRIPTION
**Pull request by juliankrispel**
cc @davegandy 

I need this to update font awesome on npm

### CODE REVIEW

**Comment by juliankrispel** [comment]
cc @tagliala @supercodepoet 

people are asking for this btw

**Comment by tagliala** [comment]
@juliankrispel sorry but this is not simple as it seems.

We should also remove tags for version 4.5.0 and I don't want this responsibility. I will send an email to Dave.

**Comment by juliankrispel** [comment]
@tagliala kk, thanks for responding

**Comment by tagliala** [comment]
Still waiting for an answer from @davegandy

**Comment by tagliala** [comment]
I'm not able to get feedback from Dave :\

**Comment by davegandy** [comment]
Sorry for the delay, folks (we were on Thanksgiving break here in the US). On this today, should have this fixed soon.

Thanks for your patience!

**Comment by davegandy** [comment]
v4.5.0 tag removed and updated to this version. Definitely let me know if there are any issues! We've got this in the checklist for next time so it doesn't happen again.

**Comment by juliankrispel** [comment]
I updated the npm module just fyi

**Comment by tagliala** [comment]
Thanks!

**Pull request merged**
