### PR TITLE
Removed Zero (0) Only

### PR DESCRIPTION
**Pull request by chandanndeep**
No need to write the 0 if we are using the unit with points.

### CODE REVIEW

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this PR.

I just want to confirm that leading 0s are correctly stripped out in the minimized css file.

We could definitely add some lints to the normal css

**Comment by chandanndeep** [comment]
@tagliala 
Take your time.

**Comment by chandanndeep** [comment]
@tagliala 
Any update?

**Comment by talbs** [comment]
Hi, @chandanndeep. Apologies for the dust that's settled on this PR. 

I can confirm that [our minimized CSS files strip out](https://github.com/FortAwesome/Font-Awesome/blob/master/css/all.min.css) these unnccessary `0`s. I'll be linting our CSS as part of our touchups and revamps with Font Awesome 6 shortly.

**Comment by chandanndeep** [comment]
No Problem.

I checked. Now issue is fixed. So am closing the topic.

Thank You,
Chandan

**Pull request closed without merging**
