### PR TITLE
Add filter heading to header

### PR DESCRIPTION
**Pull request by eelkeblok**
I was searching for this. Seems to be common enough to make it an alias?

### CODE REVIEW

**Comment by tagliala** [comment]
could you please change the alias into a filter?

**Comment by eelkeblok** [comment]
Certainly. Is there some sort of guideline what warrants an alias?

**Comment by tagliala** [comment]
aliases add a css class, so you can also use `fa-heading` in your html. Aliases increase css size

Filters only add a search tag to the docs

**Comment by tagliala** [comment]
@eelkeblok perfect, you only need to squash the commits and force push

**Comment by eelkeblok** [comment]
Thanks for the coaching. Should be all set now

**Comment by tagliala** [comment]
perfect, thanks!

It will be live when the docs will be rebuilt

**Pull request merged**
