### PR TITLE
Larger icons for icons in gh-pages !

### PR DESCRIPTION
**Pull request by ghusse**
I'm regularly having difficulties finding icons I'm looking for on the website, because icons are too tiny.

So, there is my proposal: display bigger icons. They're the most important thing to show about this project !

So be proud, show them, and make it easier to find an icon.

Before:
before

After:
after

### CODE REVIEW

**Comment by MatyCZ** [comment]
+1, its hard to find icons on this tiny icons list.

**Comment by kino90** [comment]
I currently use Stylebot addon on Google Chrome, and override css adding this 
```css
.container .col-md-4 .fa {
    font-size: 30px;
    line-height: 1.2em;
}

.fontawesome-icon-list .fa-hover a {
    margin-top: .5em;
}
.jumbotron-ad {
    padding: 20px;
}

.jumbotron-ad h1 {
    font-size: 45px;
    margin-top: 0;
}

.jumbotron-ad p {
    font-size: 17px;
    margin: 0;
}

div.fa-hover i {
    font-size: 2em;
}
```

**Comment by zecrazytux** [comment]
+1

**Comment by morteza-gho** [comment]
I Agree Too

**Comment by zuck** [comment]
+1

**Comment by My1** [comment]
+1
maybe as a kinda option that you can have them small or big.

**Comment by matiasperrone** [comment]
The +1 must be added using the +smiling face on top...

**Comment by robmadole** [comment]
First off, thanks for spending the time to post this PR. It's sat in the Font Awesome GitHub repo for far too long and we should have responded or addressed the work that you put into this.

Over the past year we've been hard at work on Font Awesome 5. It's now released and this PR no longer applies. So we're going to close it (with an apology for being so tardy).

If you think the work from this still applies feel free to reply and we'll take a second look.

– FA team

**Pull request closed without merging**
