### PR TITLE
add css to main in bower

### PR DESCRIPTION
**Pull request by hessam-nadr**

### CODE REVIEW

**Comment by tagliala** [comment]
Sorry, we are following specs

Please refer to #6227 and https://github.com/bower/spec/commit/0b34d2bb0bdd4fa31fa9728f787f49e170e41f99

**Comment by hessam-nadr** [comment]
for inject automatically by task managers like gulp this used
gulp read main of bower file and inject them into html file.

**Comment by tagliala** [comment]
Sorry, please use overrides: https://github.com/FortAwesome/Font-Awesome/pull/6227#issuecomment-141921117

**Comment by hessam-nadr** [comment]
tnx, it's correct. currently working

**Pull request closed without merging**
