### PR TITLE
Added Hover Spin Class [Cloned SPIN Class And Added Hover]

### PR DESCRIPTION
**Pull request by technofreaky**
Added A New Class Cloned By fa-spin Class

New Class Name : fa-spin-hover
it will spin when element is hovered.

### CODE REVIEW

**Comment by kkirsche** [comment]
I'd recommend rebasing or merging the current branch into this PR so that this could be auto-merged. I doubt it'll be accepted if it can't be

**Comment by technofreaky** [comment]
@kkirsche 

i don't understand what you have said can you please explain. ?

**Comment by kkirsche** [comment]
@technofreaky This pull request contains merge conflicts that must be resolved. This means that since this pull request was made, changes have occurred in master branch which means that this cannot be merged. 9 times out of 10 owners won't modify and merge someone else's pull request, meaning you would have to. This can often be done with merges or rebases.

If you are uncomfortable with these concepts I would recommend reading:
[Resolving a merge conflict from the command-line](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/)
[Resolving Conflicts](http://githowto.com/resolving_conflicts)
[Resolving Merge Conflicts from Github for Mac](https://help.github.com/articles/resolving-merge-conflicts/)
[Merging Branches from Github for Mac](https://help.github.com/articles/merging-branches/)

etc.

Honestly, your best bet will be reading up through help.github.com on those concepts than me trying to explain them

**Comment by tagliala** [comment]
This can't be merged in any case because of our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#pull-requests

> Submit all pull requests against the appropriate *-wip branch for easier merging

Since this is a non-breaking new feature, the most appropriate branch would be 4.4.0. But there is not 4.4.0 planned. so this should be done against 5.0.0-wip...

We need to address this issue

> Any changes to the styles must be made to the .less and .scss files in the src directory

/scss and /less folders are generated by the sources, so any change there will be lost

> If modifying the .less and .scss files, always recompile and commit the compiled files

You could skip this one, but since you are adding a new feature you should also provide examples in the docs

Closing here but feel free to comment if you need help

**Pull request closed without merging**
