### PR TITLE
Adds Pencil Stencil Definition.

### PR DESCRIPTION
**Pull request by gcrico**
Pencil is an "opensource tool for making diagrams and GUI prototyping that everyone can use".
@see https://code.google.com/p/evoluspencil/

The "Definition.xml" file is generated by a PHP script, that extracts names and SVG icons
from the "font-awesome.css" and "fontawesome-webfont.svg" files.

### CODE REVIEW

**Comment by rhys0178** [comment]
Hi, could we perhaps reopen this and merge please? It's a popular tool and this would be massively helpful...

**Comment by gEndelf** [comment]
+1

**Comment by konuch** [comment]
+1

**Comment by pablofullana** [comment]
+1

**Comment by grokky1** [comment]
+1

**Comment by ntbm** [comment]
+1

**Comment by goldenraphti** [comment]
+1

**Comment by santiago26** [comment]
+1

**Comment by legaultpierre** [comment]
+1

**Pull request closed without merging**
