### PR TITLE
Add tick/cross aliases

### PR DESCRIPTION
**Pull request by akx**
Ref: http://en.wikipedia.org/wiki/Check_mark
Ref: http://en.wikipedia.org/wiki/X_mark

### CODE REVIEW

**Comment by onebree** [comment]
What is the difference between `filter` and `alias`? I am asking because I am interested in adding some for other icons as well.

**Comment by tagliala** [comment]
filters are related to docs, aliases are also added to css file 

Example: https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml#L216

you can search `cog` by looking for `settings` and `gear`, you can use `fa fa-cog` and `fa fa-gear`

**Comment by onebree** [comment]
@tagliala thank you very much! This clears things up.

**Comment by tagliala** [comment]
you're welcome

Please make PR against 4.3.1-wip branch, at the moment `.yml` file on the master is corrupted

**Comment by onebree** [comment]
:+1:

**Comment by tagliala** [comment]
Merged, thanks!

**Pull request merged**
