### PR TITLE
https relevant links

### PR DESCRIPTION
**Pull request by coliff**
safer and faster

I understand that:

- [x] I'm submitting this PR for reference only. It shows an example of what I'd like to see changed but
  I understand that it will not be merged and I will not be listed as a contributor on this project.

### CODE REVIEW

**Comment by tagliala** [comment]
@coliff thanks!

**Comment by tagliala** [comment]
@coliff I've investigated this issue. Does this apply to the new docs available at https://fontawesome.com/ ?

**Comment by tagliala** [comment]
No feedback, closing here

**Comment by coliff** [comment]
Hi - sorry for delay in replying. The new docs don't have any issues - other than just a single URL which could be HTTPS which is: https://browsehappy.com/

**Comment by tagliala** [comment]
Hi @coliff 

Where can I find that link?

**Comment by coliff** [comment]
If you view source on the homepage...
```
<p class="mv0 lh-copy red2">Your browser is too old and missing some key goodies. To use the Font Awesome website, you'll need to use <a class="link fw6 white underline-hover" href="http://browsehappy.com/" target="_blank">a more modern web browser</a>.</p>
```
I guess it only shows for old IE ?

**Comment by tagliala** [comment]
Thanks. It also shows up when javascript is not available, I guess

I will report this in a private tracker

**Comment by robmadole** [comment]
On it.

**Comment by robmadole** [comment]
Fixed and will go out in the next deploy.

**Pull request closed without merging**
