### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by net-vipin**
added comment

I understand that:

- [x] I'm submitting this PR for reference only. It shows an example of what I'd like to see changed but
  I understand that it will not be merged and I will not be listed as a contributor on this project.

### CODE REVIEW

**Comment by net-vipin** [comment]
kindly approve testing

**Comment by tagliala** [comment]
Hi,

I thought this PR has been submitted by mistake

Could you please clarify?

**Comment by net-vipin** [comment]
Yes it is by mistake, i trying to learn GitHub but inside my account
repository.
Do not want any change in existing one..

**Comment by tagliala** [comment]
No problem, happy learning! 👍🏼

**Pull request closed without merging**
