### PR TITLE
Exclude icons.yml from .npmignore

### PR DESCRIPTION
**Pull request by HHogg**
**Use case**
For a custom organisation library/framework that has its own documentation (style guide) and using the Sass build to customise the class prefix. It would be nice to generate an icon list (similar to the [official list](http://fontawesome.io/icons/)) that is specific to the custom build. 

I know it could be done just by saying _"Go to the official docs, replace the `fa-` prefix for [CUSTOM PREFIX] and ignore any icons before [PACKAGE VERSION]"_ 

... but I can't see any harm in including the yaml file :smiley_cat: ... plus I'm sure there are other use cases for having access to a full list of the icons. Like in [#4851](https://github.com/FortAwesome/Font-Awesome/issues/4851)

**Note: this will also include the `license.html` and `README.md-nobuild` because they match files that are never ignored**

> The following paths and files are never ignored, so adding them to .npmignore is pointless:
> - package.json
> - README (and its variants)
> - CHANGELOG (and its variants)
> - LICENSE / LICENCE

Taken from [NPM docs](https://docs.npmjs.com/misc/developers)

### CODE REVIEW

**Comment by HHogg** [comment]
Is there any opinion on this? It's something that I feel would be very useful, with little impact or consequence.

**Comment by stefancrowe** [comment]
+1 for this

It seems there's no agreed way of generating a list of icons for a particular version of Font Awesome.

It would be even more ideal to have a JSON-formatted list of icons included for this purpose (i.e. `icons.json`). However, including the `icons.yml` would still help.

**Comment by mlazowik** [comment]
+1

We need the list of icons in our backend, would be great to generate it automatically based on whatever version of fa is installed instead of managing that manually.

**Comment by robmadole** [comment]
First off, thanks for spending the time to post this PR. It's sat in the Font Awesome GitHub repo for far too long and we should have responded or addressed the work that you put into this.

Over the past year we've been hard at work on Font Awesome 5. It's now released and this PR no longer applies. So we're going to close it (with an apology for being so tardy).

If you think the work from this still applies feel free to reply and we'll take a second look.

– FA team

**Pull request closed without merging**
