### PR TITLE
Glassdoor SVG logo added to brands

### PR DESCRIPTION
**Pull request by BeanBaag**
Glassdoor SVG has been added to brands folder. This has been tested and should be working right away.

### CODE REVIEW

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this PR.

As per [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#pull-requests)

> At the moment we are not accepting pull requests containing icons

The best thing you can do is to upvote the glassdoor request at #6422 .

If you want more information on how requests work, please take a look at our [Brand Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs)

Hope it helps

**Comment by kopax** [comment]
@tagliala we are using a font awesome pro license and we'd like to see this included in fontawesome.

Could we please know why : 

> At the moment we are not accepting pull requests containing icons

@BeanBaag thanks for sharing your work.

**Comment by tagliala** [comment]
@kopax please take a look at our [Brand Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs), you will find a lot of information on how requests work

If you need this icon right now, the best option is to [customize Font Awesome](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome)

**Comment by kopax** [comment]
Thanks for the reply and the `customize Font Awesome` link. We are using a custom icon at the moment. The `Brand Leaderboard FAQs` doesn't bring much information except there is a process to follow, but no warranty on it's execution. I hope this will be merge soon enough. Thanks for the amazing work on Font Awesome.

**Pull request closed without merging**
