### PR TITLE
Expose palm tree icon

### LINKED ISSUE #3786: Icon request: palm-tree-island
Hi,

Firstly thanks for the icon set!

I'd like to see in icon of a single palm tree on an island, it would be great to represent holiday/vacation destinations.

Thanks,
Ian

### PR DESCRIPTION
**Pull request by gotdibbs**
Fixes #3786

### CODE REVIEW

**Comment by tagliala** [comment]
Thanks but I cannot accept this PR

You could explain in #3786 how to take advantage of the 1f334 standard unicode point

**Comment by gotdibbs** [comment]
@tagliala No worries. Could you explain why for future reference? Thanks!

**Comment by tagliala** [comment]
@gotdibbs 

for various reasons: 
* those icons are not part of fontawesome
* the standard unicode set is pretty big, so we will pollute docs and dramatically increase css size
* glyphs are not consistent across browsers/platforms
* some system/platforms does not display the above icon (IE8 / XP)

image

(IE8/xp/ietester - IE11/w7 - IE9/w7)

Given that, if you need an icon from the standard unicode set (like `A`, or `%`) this is the best way to do it

**Comment by gotdibbs** [comment]
@tagliala Thanks for the detailed explanation! That all makes perfect sense.

**Pull request closed without merging**
