### PR TITLE
Added Showwcase icon

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
Please merge this PR.

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
Fixed issue #18631

**Comment by SaptarshiSarkar12** [comment]
@robmadole @tagliala Please review this PR.

**Comment by tagliala** [comment]
Hi @SaptarshiSarkar12, thanks for your willing to help and for this PR

Quoting from our [contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/6.x/CONTRIBUTING.md#pull-requests):

> At the moment we are not accepting pull requests containing icons

If you want you can customize your own set: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

(SVG + JS is the easiest way of doing it)

Hope this clarifies

Closing here but feel free to comment

**Comment by SaptarshiSarkar12** [comment]
Understood,  thanks @tagliala

**Pull request closed without merging**
