### PR TITLE
5.0.0 wip

### PR DESCRIPTION
**Pull request by CSivory**
#8770 #7650 #4519

### CODE REVIEW

**Comment by aviadhahami** [comment]
Why is this stale?
https://github.com/FortAwesome/Font-Awesome/issues/7650 is still active and getting requests

**Comment by kagansari** [comment]
@aviadhahami let's fork

**Comment by aviadhahami** [comment]
@kagansari just for this icon?

**Comment by TJProgrammer** [comment]
I've been check the changed files and it be seems that is only a version update fork...
I couldn't see any new or update icons...
Correct me if I am wrong.

**Comment by aviadhahami** [comment]
>I couldn't see any new or update icons...

+1

**Pull request closed without merging**
