### PR TITLE
Add missing t-shirt sizes to SizeProp type

### LINKED ISSUE #18788: TypeScript: Some T-shirt sizes not listed in SizeProps
TypeScript error saying that the `xl` size is invalid.
Screen Shot 2022-03-07 at 1 20 29 PM

Screen Shot 2022-03-07 at 12 35 46 PM

The docs at https://fontawesome.com/docs/web/style/size has this list of size options:
Screen Shot 2022-03-07 at 12 53 57 PM

and the fontawesome-react docs at https://fontawesome.com/docs/web/use-with/react/style#size state:
> Font Awesome supports t-shirt size scale from 2xs to 2xl as well as literal sizing from 1x to 10x.

However, looking at @robmadole's changes to `SizeProp` in https://github.com/FortAwesome/Font-Awesome/blob/65f4bdb5025759ba25cd3432568de288b6a67527/js-packages/%40fortawesome/fontawesome-svg-core/index.d.ts as part of https://github.com/FortAwesome/Font-Awesome/pull/18652, several of the sizes from the table above are missing, including `xl`.

Screen Shot 2022-03-07 at 1 03 23 PM

The icon is displaying at the correct size, so this is simply a TypeScript error.

### PR DESCRIPTION
**Pull request by daven97**
Fixes https://github.com/FortAwesome/Font-Awesome/issues/18788

### CODE REVIEW

**Review by filippofilip95 — APPROVED** [review]

**Comment by filippofilip95** [comment]
I would really appreciate it to have this merged :)

**Review by ddevsr — APPROVED** [review]

**Review by thetimehacker — APPROVED** [review]

**Comment by jkossis** [comment]
@robmadole any chance we could get this merged?

**Comment by robmadole** [comment]
We didn't accomplish this for 6.1.2 but we'll try for the next release.

**Comment by robmadole** [comment]
This has been fixed and will go out in 6.2.0.

**Comment by jkossis** [comment]
@robmadole is there a commit/pr that this fix can be linked back to? I couldn't seem to find the corresponding commit.

Would help in the closure of this ticket.

**Comment by robmadole** [comment]
This should be fixed in 6.2.0. Give it a go when you can and let me know if it doesn't fix it (I'll re-open)

**Comment by daven97** [comment]
Sorry I missed that this PR had been closed. This is working for me now in 6.2.0! Thanks!

**Pull request closed without merging**
