### PR TITLE
add style & less property to package.json

### PR DESCRIPTION
**Pull request by fiws**
Popular repos like bootstrap also have those (https://github.com/twbs/bootstrap/blob/master/package.json#L19-L20)

It can make it easier to automate stuff with Font-Awesome.

### CODE REVIEW

**Comment by tagliala** [comment]
It seems that those fields are not official... Could you please provide a use case?

https://docs.npmjs.com/files/package.json

Refers to https://github.com/twbs/bootstrap/issues/15685

**Comment by fiws** [comment]
In our case we would like to use https://www.npmjs.com/package/rework-npm and import font-awesome like ` @import "font-awesome";` 

I'm sure that there are more use cases.

**Comment by jekrb** [comment]
Hey thanks for making this pull request, I was just about to do this myself!

Any chance this can get merged + the npm publish could be updated?  It would really help my project out.  I'm using sheetify and it would be cool if I could just `@import font-awesome;`

Thanks!

**Comment by robmadole** [comment]
First off, thanks for spending the time to post this PR. It's sat in the Font Awesome GitHub repo for far too long and we should have responded or addressed the work that you put into this.

Over the past year we've been hard at work on Font Awesome 5. It's now released and this PR no longer applies. So we're going to close it (with an apology for being so tardy).

If you think the work from this still applies feel free to reply and we'll take a second look.

– FA team

**Pull request closed without merging**
