### PR TITLE
src/icons.yml: add fullscreen filter

### PR DESCRIPTION
**Pull request by williamboman**

### CODE REVIEW

**Comment by tagliala** [comment]
Since icons.yml in the master branch is corrupted, do you mind to push against `4.3.1-wip` branch?

sorry for this, we changed our contributing guidelines so it should not happen again

**Comment by williamboman** [comment]
Sure! I was unsure which branch to push to :smile: <sup>*cough* #5774</sup>

**Comment by tagliala** [comment]
@williamboman this is only about the icons.yml file :sweat:

**Comment by williamboman** [comment]
Sure, but the markdown can be changed to `4.3.1-wip` until it's fixed, then back to `master`. I think it would be nice to have some sort of documentation on how to contribute with alias/filter suggestions.

**Comment by tagliala** [comment]
this could be done in the master branch, but at the moment the master branch has a corrupted icons.yml file. Unfortunately Dave is very busy at the moment, I don't know when 4.3.1 will be released

**Comment by williamboman** [comment]
Not sure if I'm misunderstanding you, but I was speaking more generally about guidelines for contributing with filter/alias suggestions. (PR at #5774)

**Comment by tagliala** [comment]
@williamboman sorry, I misunderstood you. Thanks for the PRs

**Comment by williamboman** [comment]
Happy to help :)

**Pull request closed without merging**
