### PR TITLE
fixes issue #6552

### PR DESCRIPTION
**Pull request by bsara**
I created two new files: `_variables-patch.scss` and `font-awesome-patched.scss`. Having the later will likely reduce confusion for users who want to make sure they are doing imports correctly to use the patch provided.

### CODE REVIEW

**Comment by tagliala** [comment]
Awesome, thanks!

Just another little thing... I'm not an English native speaker, do you mind to add an heads up here to describe this issue: http://fontawesome.io/get-started/ ?

Something like

```html
<p class="alert alert-success"><i class="fa fa-exclamation-triangle"></i> SASS has <a href="https://github.com/sass/sass/issues/659">an issue</a> with escaping in variables. If you are using SASS 3.4.0+, please include `font-awesome-patched.scss`</p>
```

in `PRO: Custom LESS or SASS`

**Comment by bsara** [comment]
no problem. I'll add it to this pull request.

**Comment by bsara** [comment]
@tagliala sorry that it took me a couple of days to get to this, but the docs have been updated.

**Comment by bsara** [comment]
@tagliala wait, I forgot to add one more thing! sorry.

**Comment by bsara** [comment]
@tagliala actually, nevermind. Unless you want the warning on the page twice (it's currently only under "Easy: Sass Ruby Gem"...don't know if you also want it under "PRO: Custom LESS or Sass" as well).

**Comment by tagliala** [comment]
@bsara maybe both.... for sure under the PRO:, don't know the easy. that's another repo: https://github.com/FortAwesome/font-awesome-sass

**Comment by bsara** [comment]
@tagliala oh man, I didn't even realize that repo existed. why is the code duplicated in both locations? they should either be consolidated into one repo or the sass repo should be a submodule in this main repo. Thoughts?

**Comment by bsara** [comment]
@tagliala I've added the warning to both sections of the get started page. I also took the liberty of cleaning up that page's HTML and separated it out into included sections like the other pages have done. Hope that's helpful to you. As for the other repo, I can make the changes there as well, won't take long at all. Is that something that you guys want? I noticed that there was no 4.3.1-wip branch on that repo so I don't know what you do to update it.

**Comment by bsara** [comment]
here are some screenshots so that you don't have to build the whole thing just to look at my changes visually:

image

---

image

**Comment by tagliala** [comment]
I have troubles on the `-patched` suffix. What do you think about `-sass340` ? It would be self explanatory

**Comment by bsara** [comment]
I named it `-patched` so that if any other patches are needed in the future, they can be added there. But I don't own the project, if you guys want `-sass340`, I'd be happy to do that.

**Comment by bsara** [comment]
@davegandy, is there a specific reason this has been closed and not merged?

Thanks.

**Comment by tagliala** [comment]
@bsara the branch 4.3.1 was deleted in favour of 4.4.0, Dave didn't explicitly close this PR

I still think this is an issue and should be addressed in the next release

**Pull request closed without merging**
