### PR TITLE
Added space after # in README.md

### PR DESCRIPTION
**Pull request by macmladen**
Added space after # in README.md for consistency and proper appearance on npmjs.com project page.

It seems that **npmjs.com** requires a space after # to properly generate **heading** tag.

Also in **CONTRIBUTE.md** there is a space after so this also adds to consistency.

### CODE REVIEW

**Comment by tagliala** [comment]
Hi,

thanks for this PR

You should edit: https://github.com/FortAwesome/Font-Awesome/blob/master/src/README.md-nobuild because `README.md` is automatically generated

Keeping this open

**Comment by macmladen** [comment]
Not sure if you are notified of a new push, I changed `README.md-nobuild` too.

Just old school DTP so I had problem with bad page on npmjs.com.

It is also too often suggested that libraries (and FontAwesome) should be included using `bower` while most can be included with `npm`. Maybe it should be stressed in README?

**Comment by tagliala** [comment]
please squash commits and push force, so I can merge

> It is also too often suggested that libraries (and FontAwesome) should be included using bower while most can be included with npm. Maybe it should be stressed in README?

feel free to create a new PR

**Comment by macmladen** [comment]
I think I fixed the PR so it is now one commit ready to be merged.

**Comment by tagliala** [comment]
thanks!

**Pull request merged**
