### PR TITLE
Release 6.5.0

### PR DESCRIPTION
**Pull request by deathnfudge**

### CODE REVIEW

**Comment by evertharmeling** [comment]
Was the directory structure change done on purpose in the `6.5.0` release? Since `6.5.0` all assets reside in a `free` folder, this would be considered **backwards incompatible** for a minor right? It's also not mentioned in the [CHANGELOG.md](https://github.com/FortAwesome/Font-Awesome/blob/6.x/CHANGELOG.md), or did I miss something?

See [6.5.0](https://github.com/FortAwesome/Font-Awesome/tree/6.5.0) vs [6.4.2](https://github.com/FortAwesome/Font-Awesome/tree/6.4.2)

**Comment by tagliala** [comment]
Thanks, this is a good point. Deserves a new issue, I opened #20029

**Comment by evertharmeling** [comment]
Cool, wasn't sure as nobody mentioned it after the release 2 days ago :). Thanks for the fast response!

**Comment by tagliala** [comment]
I think it mostly depend on usage and this is breaking some edge case that we did not consider.

Any chance to clarify the use case that this is breaking? 

Is this relying to the position of a file in the source code?

**Comment by evertharmeling** [comment]
Yes, I elaborated on it in https://github.com/FortAwesome/Font-Awesome/issues/20029#issuecomment-1833679626

**Pull request merged**
