### PR TITLE
4.3.1 wip #1685 .fa-ok, #1609 .fa-ya

### PR DESCRIPTION
**Pull request by iegik**
[Odnoklassniki.ru](http://odnoklassniki.ru) (ok.ru, apiok.ru) - Russian's and [Near abload's](https://en.wikipedia.org/wiki/Near_abroad) social network. (same as Vkontakte `.fa-vk`)
[Yandex.ru](http://yandex.ru) (ya.ru) - Russian's and [Near abload's](https://en.wikipedia.org/wiki/Near_abroad) only search provider. (like Google `.fa-google` in US)
[read more...](https://www.2checkout.com/blog/article/understanding-russian-social-media-vkontakte-odnoklassniki)

***

`.fa-ok` - Odnoklassniki logo, for sharing user profile in portfolio or sharing something with friends using [API](http://apiok.ru)
`.fa-ok-square` - same as above, but inverted with squared background.

`.fa-ya` - for marking Yandex online tools: searching API, news, and so on.
`.fa-ya-square` - same as above.

### CODE REVIEW

**Comment by iegik** [comment]
I know rules. Please do not close this request.

**Comment by tagliala** [comment]
@iegik I really thank you for you efforts. I can keep this open but I can't merge, sorry

**Comment by Luntegg** [comment]
Doesn't work.. Empty square instead of any icon.

**Comment by Luntegg** [comment]
Awesome! Thanks! I checked font for this almost every day!

**Comment by matyunin** [comment]
:+1:

**Pull request closed without merging**
