### PR TITLE
attempt at lanyrd icon

### PR DESCRIPTION
**Pull request by h4ck3rm1k3**
This is obviously wrong, but I need some instructions.

attached is my attempt at lanyrd, I created on master and attempted to rebase on 4.2.1 wip

### CODE REVIEW

**Comment by h4ck3rm1k3** [comment]
attempt at #1653

**Comment by tagliala** [comment]
@h4ck3rm1k3 thanks for this PR

At the moment we are not accepting PR containing icons, as per our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#pull-requests

**Comment by tagliala** [comment]
I've checked your PR, but that should not be the proper way to add an icon to FA.

(disclaimer: I'm not in charge of making icons)

The workflow should the following:
* Prepare your development machine (you will need ruby, less and jekyll)
* Clone the master branch
* Edit the .otf file here: https://github.com/FortAwesome/Font-Awesome/blob/master/src/assets/font-awesome/fonts/FontAwesome.otf (take a look at this guide: https://github.com/blog/1135-the-making-of-octicons)
* Edit icons.yml here: https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml
* Upload the otf at fontsquirrel to generate the webfont: http://www.fontsquirrel.com/tools/webfont-generator
* Regenerate less and scss and css via `jekyll build` (do not edit `/less` and `/scss` folders, they are generated)


Hope this helps

**Comment by h4ck3rm1k3** [comment]
OK thanks for the instructions. I am going to try it out.

**Comment by tagliala** [comment]
You're welcome. Feel free to ask if you need more info

**Comment by h4ck3rm1k3** [comment]
The font squirrel site does not have the Add Font button activated. my font custom output is here https://github.com/KansasLinuxFest/Font-Awesome/tree/ec00ee61aaceb4c3a1957b43bcf494aa735a2e72/fonts/lanyrd/fontcustom

**Comment by h4ck3rm1k3** [comment]
Also I do not have photoshop, I am a free software advocate. Are you saying we need to install adobe to contribute to this project? If so I dont want to do that.

**Comment by tagliala** [comment]
@h4ck3rm1k3 at the moment you can't contribute, as I said before PR with icons will not be merged. The build of FontAwesome is currently based on the `.otf` file.

There are others projects which have an open build process based on the `.svg` format

**Comment by h4ck3rm1k3** [comment]
well thanks for your feedback, am going to have to do some reading up on all this.

**Comment by tagliala** [comment]
you're welcome.

The binary nature of the .otf file is one (not the only, of course) of the concerns because FA hasn't an open build process. There is a request  to switch to svg here #3065 

I agree with #3065, but this decision isn't up to me, sorry

**Pull request closed without merging**
