### PR TITLE
Reverse changelog order

### PR DESCRIPTION
**Pull request by honzi**
Hello. I think it makes more sense to order the changelog starting with the most recent update.

### CODE REVIEW

**Comment by tagliala** [comment]
sure it is, thanks!

**Comment by tagliala** [comment]
Sorry.

I didn't check this PR. You should have edited `src/README.md`, since `README.md` is generated.

I will take care of reversing the order

**Comment by honzi** [comment]
Whoops, my bad. Sorry about that.

**Comment by tagliala** [comment]
no problem

**Pull request merged**
